services:
  mysql:
    container_name: 'todolist'
    image: 'mysql:8.0.38'
    environment:
      - 'MYSQL_DATABASE=todolist'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=devuser'
    ports:
      - '3306'